# Generated by Django 3.2.2 on 2021-05-10 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='P<built-in function id>', max_length=100)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_prices', to='home.product')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
