# Generated by Django 3.2.2 on 2021-05-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_productsold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_sold',
        ),
        migrations.AddField(
            model_name='order',
            name='product_sold',
            field=models.ManyToManyField(to='home.ProductSold'),
        ),
    ]
